- name: mysql
  hosts: mysql
  become: yes
  vars:
    root_password: ExpenseApp@1
    host: mysql.daws82srinu.online
  tasks:
    - name: ansible to install software
      ansible.builtin.pip:
        name: 
        - PyMySQL
        executable: pip3.9
  # - name: Install MySQL/MariaDB server
  #   ansible.builtin.package:
  #     name: "{{ 'mysql-server' if ansible_os_family == 'Debian' else 'mariadb105-server' }}"
  #     state: present

  # - name: Start MySQL/MariaDB service
  #   ansible.builtin.service:
  #     name: "{{ 'mysql' if ansible_os_family == 'Debian' else 'mariadb' }}"
  #     state: started
  #     enabled: true

    - name: mysql installation
      ansible.builtin.package:
        name: mysql-server
        state: present

    - name: start my mysql server
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    
    - name: connect my sql server
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ root_password }}"
        login_host: "{{ host }}"
      ignore_errors: true
      register: mysql_info

    - name: mysql_info print
      ansible.builtin.debug:
        msg: "{{ mysql_info }}"