- name: backend steps
  hosts: backend
  become: yes
  tasks:
  - name: steps of mysql
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs
    ansible.builtin.command: dnf moduel enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: user
    ansible.builtin.user:
      name: expense